version: '3'

networks:
    network:
        
volumes:
    app:
        name: ${COMPOSE_PROJECT_NAME}_app_volume
        driver: local
        driver_opts:
            type: nfs
            o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
            device: ":/System/Volumes/Data/${PWD}/src/"

    mysql:
        name: ${COMPOSE_PROJECT_NAME}_mysql_volume
        
services:
    app:
        image: sentrasoft/laravel:php8.1-fpm
        container_name: ${COMPOSE_PROJECT_NAME}_app
        working_dir: /var/www
        environment:
            - "TZ=Asia/Jakarta"
        volumes:
            - app:/var/www
        networks:
            - network

    mysql:
        image: mysql:8.0
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        volumes:
            - ./.data:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=laravel"
            - "MYSQL_USER=trooper"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        tty: true
        ports:
            - "3392:3306"
        networks:
            - network

    nginx:
        image: nginx:1.15.8
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        volumes:
            - ./.config/.nginx:/etc/nginx/conf.d/default.conf
            - ./.ssl/local.cert:/etc/ssl/certs/local.cert
            - ./.ssl/local.key:/etc/ssl/certs/local.key
            - app:/var/www
        depends_on:
            - app
            - mysql
        working_dir: /var/www
        ports:
            - "8092:80"
            - "4392:443"
        networks:
            - network
