version: '2'
services:

  app:
    image: sentrasoft/laravel:php7.2-fpm
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    networks:
      - laravel

  web:
    image: nginx:1.15.8
    volumes:
      - ./:/var/www
      - .nginx:/etc/nginx/conf.d/default.conf
      - ./ssl/local.cert:/etc/ssl/certs/local.cert
      - ./ssl/local.key:/etc/ssl/certs/local.key
    working_dir: /var/www
    ports:
      - "8080:80"
      - "8443:443"
    networks:
      - laravel

  database:
    image: mysql:5.7
    volumes:
      - database:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=laravel"
      - "MYSQL_USER=root"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
        - "3306:3306"
    networks:
      - laravel

volumes:
  database:

networks:
  laravel:
    driver: bridge
