version: '3'

networks:
    network:
        
volumes:
    mysql:
        
services:
    app:
        image: sentrasoft/laravel:php8.0-fpm
        container_name: ${COMPOSE_PROJECT_NAME}_app
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - network

    mysql:
        image: mysql:5.7
        container_name: ${COMPOSE_PROJECT_NAME}_mysql
        volumes:
            - ./.data:/var/lib/mysql
        environment:
            - "MYSQL_DATABASE=laravel"
            - "MYSQL_USER=trooper"
            - "MYSQL_PASSWORD=secret"
            - "MYSQL_ROOT_PASSWORD=secret"
        tty: true
        ports:
            - "3306:3306"
        networks:
            - network

    nginx:
        image: nginx:1.15.8
        container_name: ${COMPOSE_PROJECT_NAME}_nginx
        volumes:
            - ./src:/var/www
            - ./.ssl/local.cert:/etc/ssl/certs/local.cert
            - ./.ssl/local.key:/etc/ssl/certs/local.key
            - ./.nginx:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
            - mysql
        working_dir: /var/www
        ports:
            - "8080:80"
            - "8443:443"
        networks:
            - network
